spring.application.name=eventu
server.error.include-stacktrace=never
debug=true

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5434}/${PGDATABASE:eventu}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:Its2025!}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
#spring.jpa.properties.hibernate.format_sql=true


