spring.application.name=eventu
server.error.include-stacktrace=never

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url = jdbc:postgresql://localhost/eventu_db
spring.datasource.username = postgres
spring.datasource.password = Its2025!
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
#spring.datasource.database-platform = postgres
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

## Hibernate Properties
spring.jpa.properties.hibernate.show_sql = true
spring.sql.init.mode=always

# Hibernate ddl auto (create, create-drop, validate, update, none)
spring.datasource.url=jdbc:postgresql://localhost:5432/eventu
spring.datasource.username=postgres
spring.datasource.password=Its2025!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true